apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.sync-operation-change.gchat: spaceName
spec:
  project: default
  source:
    path: DeploymentHelm/kube-prometheus-stack
    helm:
      version: v3
      releaseName: kube-prometheus-stack
      valueFiles:
      - values.yaml
      skipCrds: false
    repoURL: https://github.com/shivam199064/Argocd-Setup.git
    targetRevision: HEAD
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  # ignoreDifferences:
  # - group: monitoring.coreos.com
  #   kind: ServiceMonitor
  #   jqPathExpressions:
  #   - .spec.endpoints[]?.relabelings[]?.action