apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myprometheus
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.sync-operation-change.gchat: spaceName
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: default
  source:
    path: Prometheus/
    repoURL: https://github.com/shivam199064/Deployment.git
    targetRevision: HEAD
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
      

