apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mywebapplication
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.sync-operation-change.gchat: spaceName
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: deployment/
    repoURL: https://github.com/shivam199064/test.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      

