{
 "title": "Karpenter",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "options": {
    "content": "![argoimage](https://res.cloudinary.com/practicaldev/image/fetch/s--fWGvWtx5--/c_imagga_scale,f_auto,fl_progressive,h_900,q_auto,w_1600/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/1ec2mb193n6r2zfn2f7z.jpg)"
   },
   "targets": [
    {}
   ]
  },
  { "title": "EKS Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Number Of Nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_info{node=~\".*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Instance-type",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (label_beta_kubernetes_io_instance_type)(kube_node_labels{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Capacity-Type",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (capacity_type) ((label_replace((kube_node_labels{label_karpenter_sh_capacity_type=\"\"}), \"capacity_type\", \"$1\", \"label_eks_amazonaws_com_capacity_type\" ,\"(.*)\")) or label_replace((kube_node_labels{label_karpenter_sh_capacity_type!=\"\"}), \"capacity_type\", \"$1\", \"label_karpenter_sh_capacity_type\" ,\"(.*)\"))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodes Provisioned by Karpenter",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (label_karpenter_sh_provisioner_name) (kube_node_labels{label_karpenter_sh_initialized=\"true\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Provisioned By Karpenter",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_node_labels{label_karpenter_sh_capacity_type!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Provisioner Details",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 11 },
   "targets": [
    {
     "expr": "sum by (label_karpenter_sh_provisioner_name,label_node_kubernetes_io_instance_type,label_karpenter_sh_capacity_type ) (kube_node_labels{label_karpenter_sh_initialized=\"true\"})",
     "legendFormat": "{{provisioner_name}}"
    }
   ]
  },
  {
   "title": "Provisioned By Other",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_node_labels{label_karpenter_sh_capacity_type=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node-Details Provisioned by Karpenter",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum by (label_kubernetes_io_hostname, label_karpenter_sh_provisioner_name, label_karpenter_k8s_aws_instance_pods) (kube_node_labels{label_karpenter_sh_initialized=\"true\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (label_kubernetes_io_hostname) (label_replace(karpenter_pods_state{phase=\"Running\"}, \"label_kubernetes_io_hostname\", \"$1\", \"node\", \"(.*)\"))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}