apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  service.webhook.gchat: |
    url: $webhook-url
    headers:
    -name: "Content-Type"
    value: "application/json"
  template.sync: |
    webhook:
      gchat:
        method: POST
        body: |
          {
          "text": "The app *{{ .app.metadata.name }}* has *successfully synced!*"
          }
  template.fail: |
    webhook:
      gchat:
        method: POST
        body: |
          {
          "text": "The app *{{ .app.metadata.name }}* has *fail!* "
          }
  template.out: |
    webhook:
      gchat:
        method: POST
        body: |
          {
          "text": "The app *{{ .app.metadata.name }}* has *OutOfSync!* "
          }

  template.prune: |
    webhook:
      gchat:
        method: POST
        body: |
          {
          "text": "The app *{{ .app.metadata.name }}* health status is in *Progressing* mode So we need to *prune* old deployment! "
          }
          
  trigger.sync-operation-change: |
    - when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy' and app.status.sync.status != 'OutOfSync'
      oncePer: app.status.sync.revision
      send: [sync]
    - when: app.status.operationState.phase in ['Error', 'Failed']
      send: [fail]
    - when: app.status.sync.status in ['OutOfSync']
      send: [out]
    - when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Progressing'
      send: [prune]