apiVersion: argoproj.io/v1alpha1
kind: Workflow                  #new type of k8s spec
metadata:
  name: instance-restart 
spec:
  workflowMetadata:
      labels:
        workflows.argoproj.io/archive-strategy: "always"
      suspend: true
      workflowSpec:
        ttlStrategy:
          secondsAfterCompletion: 1800
      entrypoint: script-template
      serviceAccountName: workflow
  templates:
  - name: script-template
    script: 
      image: python:3.8-slim
      command: [python]
      source: |
        print("successfully execute by shivam")