- apiVersion: bitnami.com/v1alpha1
    kind: SealedSecret
    metadata:
        creationTimestamp: null
        name: argocd-notifications-secret
        namespace: argocd
    spec:
        encryptedData:
            webhook_url: AgAmUYGQjVzXg1O35dv4SgJ6JJD9AjsX/b8QGXnKXJcqE+TrxOf+fCAxZvvUVGzgBb0MGuc+PY5HNsXWWN40ilTwR1LX6yVEEG8oxGTu8zj4i8WDEKSGxJiNSfyHjDFQmvH/wyEcmjU5r89Kb9HXBw6Xa2bXiCK56daTuqpge3Mp/gMssBIGak3flkPVNjw2lhgfF/SxI7Ngd+DTNZVvaeF0VeU4kKQsibQjnfBIMm3f+yyaJb6KdDVJkOpeCZhCgaHopZmS3CZNpeJ9Os1us8RBhGYDQ0KX+9XkydBNdM95atmzJl6tI49CXNYRntbb2WJn6Vih0wqABsREoneFJevzc6U6KmaDMCW1sAmiABeIFPqRKcOhyH7Fju67HClof+9llGXCDdRHgVJZ4Tupdtqm46MHF8KAp0xZ0hgv84X0tjT86NSp3bBebHl9vl/ujPzEzbYtxkExDi5hICSupBYT96g6yp6l8fVy0DWKiH/DkUVpCj5rWD13lEmIi02ErxxDbN7UyaehQyoclzsnwfDsGpQVX5F6fjjiB7nIZu2GectRGUMnhQkGLb8AtIeVju62kRapVuYRFdoYM/lk2R0JXrd6CHX71/x4XouCW38k0glk6a3htm/FIOkNdfCf/uF/xIsa4l5NM/KZ6U+aHh11jX63qF5YfHeOc/gSxaZTaWb4aqiSYq13kkRCGoLyLxbs9JDl3LxWMZcO8k6eUJeBs16PlNbnVwTf3t5Yx353CwwN8Lk+rxFKv/y9oTvzOuHLtjFIoA7HGc8PhD3OweJ9ubhjnWZLMtaX8GNlRciwB/2Zq+eI7WDvazBSIQl0lHOVhw2xHQY847Me6G14QelX9ckrsRXzWV9oOKb93K+gpILHgcg9xL1ltbo7+INTCwAYgT9koOFLoQ==
        template:
            metadata:
                creationTimestamp: null
                name: argocd-notifications-secret
                namespace: argocd
            type: Opaque